### ISSUE TITLE
Anvil dupe

### ISSUE THREAD

**Issue by Sereath** [ACGaming/CursedItemEntities#2]
I first noticed this when player Knifethrust duped an HBM anvil by accident and reported it to me.

Clean instance, except for Had Enough Items:

https://gfycat.com/educatedwidegelding

And sometimes it wouldn't happen.

https://gfycat.com/knobbyfoolishheterodontosaurus

latest.log
https://mclo.gs/uECadBS

debug.log
https://mclo.gs/YHoXB3V

**Comment by ACGaming** [comment]
Oh, this is interesting! Thanks for the detailed report.

**Comment by ACGaming** [comment]
I‘ve decided to remove falling blocks dropping as items since it duped regular blocks as well (although very rarely). Falling blocks will instead try to move nearby item entities by colliding with them which isn‘t perfect but a failsafe way for now.
